### ISSUE TITLE
publishing Week2 homework

### ISSUE THREAD

**Issue by neveenatik** [HackYourFuture/JavaScript3#34]
According to week2 homework instruction. students weren't able to publish the homework on github pages. that's because github publishes only from master or a branch called gh-pages.
so there is a solution by letting students make a branch for each week from master (week1, week2, week3) and this extra branch (gh-pages) need to be created for publishing purpose only.
But then homework needs to be added twice once in week branch and once in gh-pages.
My question is: is this needed?
Making a branch for each week if yes then the solution is to submit homework twice. If not then homework can be submitted to one branch gh-pages that gets updated each week.

**Comment by remarcmij** [comment]
Hi Neveen, you should create a PR for your homework against your `week1`, `week2` or `week3` branch. The `gh-pages` branch is not related to homework submission; it is just a handy way to show your homework in action. (When writing the assignment I had not taken the `gh-pages` option into account.)

Since the JS3 homework is about a single application that implements the same functionality in more advanced ways throughout the three weeks, you can always publish your latest version through gh-pages. (Note that a GitHub branch is just a pointer to a specific commit.) If anyone wants to know details about the versions of previous weeks they can always look at the branches in the repo or clone your repo and run the different versions locally. So when you have committed your latest changes into your homework branch I would just merge that branch into the gh-pages branch for publication purposes.

Does this address your issue?

**Comment by neveenatik** [comment]
Hi Jim, Yes indeed so everyweek I merge the branch I made for that week with gh-pages instead of adding homework on both branches.
